// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using UrbanSpork.DataAccess.DataAccess;

namespace UrbanSpork.DataAccess.Migrations
{
    [DbContext(typeof(UrbanDbContext))]
    [Migration("20180131032724_stephen")]
    partial class stephen
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("UrbanSpork.DataAccess.DataAccess.UserEvents", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("EventType");

                    b.Property<string>("OldUserDTO")
                        .HasColumnType("json");

                    b.Property<DateTime>("TimeStamp");

                    b.Property<string>("UpdatedUserDTO")
                        .HasColumnType("json");

                    b.Property<int>("Version");

                    b.HasKey("Id");

                    b.ToTable("UserEvents");
                });

            modelBuilder.Entity("UrbanSpork.DataAccess.DataAccess.Users", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Access")
                        .HasColumnType("json");

                    b.Property<string>("Department");

                    b.Property<string>("Email");

                    b.Property<string>("Equipment")
                        .HasColumnType("json");

                    b.Property<string>("FirstName");

                    b.Property<DateTime>("InitialApprovedDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive");

                    b.Property<string>("LastName");

                    b.Property<string>("Position");

                    b.HasKey("UserID");

                    b.ToTable("Users2");
                });
#pragma warning restore 612, 618
        }
    }
}
