// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using UrbanSpork.API.Data;

namespace UrbanSpork.API.Migrations
{
    [DbContext(typeof(USDbContext))]
    [Migration("20180118203840_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UrbanSpork.API.Data.UserRM", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Assets")
                        .HasColumnType("jsonb");

                    b.Property<string>("Department");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<bool>("IsActive");

                    b.Property<string>("LastName");

                    b.Property<string>("Position");

                    b.HasKey("UserID");

                    b.ToTable("UserRM");
                });
            modelBuilder.Entity("UrbanSpork.DataAccess.DataAccess.userevents", b =>
            {
                b.Property<string>("id").ValueGeneratedOnAdd();
                b.Property<string>("firstName");
                b.HasKey("id");
                b.ToTable("userevents");
            });
#pragma warning restore 612, 618
        }
    }
}
